# Generated by Django 4.0.4 on 2022-05-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('brand', models.CharField(max_length=124)),
                ('color', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('purchase_date', models.DateField()),
                ('sale_date', models.DateField(null=True)),
                ('car', models.ManyToManyField(to='AutoCar.car')),
            ],
        ),
        migrations.CreateModel(
            name='Usercar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoCar.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoCar.user')),
            ],
        ),
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_type', models.IntegerField(choices=[(1, 'uzupełnienie oleju silnikowego'), (2, 'uzupełnienie płynu hamulcowego'), (3, 'uzupełnienie płynu do spryskiwaczy')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoCar.car')),
            ],
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.IntegerField(choices=[(1, 'Benzyna 95'), (2, 'Benzyna 98'), (3, 'Benzyna 100'), (4, 'Diesel B7'), (5, 'Diesel B10'), (6, 'Diesel XTL'), (7, 'Gaz')])),
                ('amount_fueled', models.FloatField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kilometers_traveled', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoCar.car')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.IntegerField(choices=[(1, 'przegląd techniczny'), (2, 'filtr oleju'), (3, 'filtr powietrza'), (4, 'klocki hamulcowe'), (5, 'filtr paliwa'), (6, 'tarcze hamulcowe'), (7, 'filtr kabinowy'), (8, 'akumulator'), (9, 'rozrząd'), (10, 'zmiana na opony letnie'), (11, 'zmiana na opony zimowe')])),
                ('change_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoCar.car')),
            ],
        ),
    ]
